name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - core24_support

jobs:
  unit: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install crun
      uses: ./.github/actions/fix-crun
      with:
        checksums: CHECKSUMS
    - run: |
        npm install
        npm run all

  docker-integration: # make sure the action works on a clean machine without building
    strategy:
      fail-fast: false
      matrix:
        base:
          - core18
          - core20
          - core22
          - core24
        arch:
          - armhf
          - arm64
        runner:
          - ubuntu-latest
        include:
          - base: core
            arch: armhf
            runner: ubuntu-20.04
          - base: core
            arch: arm64
            runner: ubuntu-20.04
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: docker/setup-qemu-action@v3
      with:
        image: 'tonistiigi/binfmt:master'
    - uses: actions/checkout@v4
    - name: Install crun
      uses: ./.github/actions/fix-crun
      with:
        checksums: CHECKSUMS
    - uses: ./
      id: snapcraft
      with:
        path: './test-projects/${{ matrix.base }}'
        architecture: ${{ matrix.arch }}
